spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/1196013153/cloud-config.git
          username: 1196013153
          password: ye19980514
server:
  port: 6060