eureka:
  client:
    service-url:
      defaultZone: http://192.87.18.31:8761/eureka/
  # 自定义实例编号
  instance:
    # 优先使用IP地址方式进行注册服务
    prefer-ip-address: true
server:
  port: 8098
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
spring:
  application:
    name: eureka-provider
  sleuth:
    sampler:
      probability: 1.0
#  profiles:
#    active: peer1,peer2