eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  # 自定义实例编号
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
server:
  port: 7083
spring:
  application:
    name: eureka-feign
management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.example.feign.service.HelloService: debug