spring:
  profiles:
    active: after_route

---
server:
  port: 8081
spring:
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: http://httpbin.org:80/get
          predicates:
            - Method=GET
            - Before=2020-01-20T17:42:47.789-07:00[America/Denver]
  profiles: after_route