eureka:
  client:
    service-url:
      defaultZone: http://ye1998.host:8761/eureka/
server:
  port: 8082
spring:
  application:
    name: eureka-ribbon
#可以打开所有的监控点
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
  shutdown:
    enabled: true